name: Aplicação Django

on: [pull_request]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Instalar Depedências
        run: |
          pip install pipenv
          pipenv sync --dev
      - name: Rodar Testes Automáticos
        run: |
          pipenv run pytest well
      - name: Cobertura de teste
        run: |
          pipenv run pytest --cov=well
      - name: Carregar Relatórios para Codecov
        run: |
          pipenv run codecov